spring.application.name=API
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-jolly-credit-aczkxb94-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_twq8hzcN1RXO}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
api.security.token.secret=${JWT_SECRET:Fe201820}