# Configuração para o Banco de Dados na Nuvem (Neon)
spring.datasource.url=jdbc:postgresql://ep-purple-waterfall-aeddy1pz.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QLkw3NcjM4DV
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - Criar as tabelas automaticamente na primeira vez
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Segurança - JWT (Troque essa secret depois por algo difícil!)
api.security.token.secret=${JWT_SECRET:minha-senha-secreta-muito-dificil}